### PR TITLE
changed prompt symbol

### PR DESCRIPTION
**Pull request by caarlos0**
screen shot 2015-10-03 at 7 31 00 pm

looks better?

### CODE REVIEW

**Comment by fdaciuk** [comment]
I use this arrow xD
:+1: 

selection_151

**Comment by caarlos0** [comment]
@fdaciuk can you paste the char here?

**Comment by fdaciuk** [comment]
➜
this ;)

**Comment by caarlos0** [comment]
@fdaciuk check it out

**Comment by fdaciuk** [comment]
Nice! :dancer: :dancer: :sparkles: 
:shipit:

**Comment by caarlos0** [comment]
@fdaciuk thanks

**Pull request merged**
