### PR TITLE
Add aliases

### PR DESCRIPTION
**Pull request by cunhazera**
- When I use git I miss an alias to `git clone`
- What do you think about the changing in the status command?

### CODE REVIEW

**Comment by caarlos0** [comment]
I don't really like to change aliases because I'm used to the ones I already have.

Adding the git clone alias is fine though...

**Comment by cunhazera** [comment]
@caarlos0 check it out

**Comment by caarlos0** [comment]
Nice, tnx.

BTW: you can add custom aliases in `~/.localrc` if you want ;) - https://github.com/caarlos0/dotfiles#personalization

**Comment by cunhazera** [comment]
Ok, tnks :+1:

**Pull request merged**
