### PR TITLE
replaced antigen with antibody

### PR DESCRIPTION
**Pull request by caarlos0**
https://github.com/caarlos0/antibody

### CODE REVIEW

**Comment by oieduardorabelo** [comment]
this is amazing :tada: 

congratulations my friend, nice idea!

**Comment by caarlos0** [comment]
@oieduardorabelo and 5x faster on my machine :balloon:

**Comment by caarlos0** [comment]
@rultor release, tag=`1.5.0`

**Comment by marcel-dias** [comment]
👏👏👏 Congrats man. It is really fast.

**Pull request merged**
